//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoTerapeutica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedsLarEntities : DbContext
    {
        public MedsLarEntities()
            : base("name=MedsLarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Direccaos> Direccaos { get; set; }
        public virtual DbSet<Farmacias> Farmacias { get; set; }
        public virtual DbSet<Funcionarios> Funcionarios { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<Patologias> Patologias { get; set; }
        public virtual DbSet<ReservaFarmacoes> ReservaFarmacoes { get; set; }
        public virtual DbSet<Utentes> Utentes { get; set; }
    }
}
