//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoTerapeutica
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaFarmacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaFarmacoes()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
            this.Medicos = new HashSet<Medicos>();
        }
    
        public int ReservaId { get; set; }
        public int CNP { get; set; }
        public string LinkRCM { get; set; }
        public int PosologiaDia { get; set; }
        public int PosologiaSemana { get; set; }
        public int PosologiaMes { get; set; }
        public float Existencias { get; set; }
        public int UtenteFK { get; set; }
        public int FarmaciaFK { get; set; }
    
        public virtual Farmacias Farmacias { get; set; }
        public virtual Utentes Utentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicos> Medicos { get; set; }
    }
}
