//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoTerapeutica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utentes()
        {
            this.ReservaFarmacoes = new HashSet<ReservaFarmacoes>();
            this.Direccaos = new HashSet<Direccaos>();
        }
    
        public int UtenteId { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public Nullable<int> Patologias_IdPatologia { get; set; }
    
        public virtual Patologias Patologias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaFarmacoes> ReservaFarmacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccaos> Direccaos { get; set; }
    }
}
